version: '1.0'
services:
  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_DATABASE: 'pokemon'
      MYSQL_ROOT_PASSWORD: 'geheim1234'
    ports:
      - '6033:3306'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      - PMA_HOST db
      - PMA_PORT 3306
      - PMA_ARBITRARY 1
    restart: always
    ports:
      - 8081:80
  my-apache:
    container_name: my-apache
    image: my-apache-image
    ports:
      - '8080:80'
    build:
      context: ./apache
      dockerfile: Dockerfile
